apiVersion: v1 
kind: Pod 
metadata:
  labels:
    name: nginx-web
  name: nginx-web 
spec:
  containers:
    - image: nginx:alpine
      name: nginx-web 
      ports:
       - containerPort: 80 
         name: http 
         protocol: TCP
